django-demo-estate-property/homefinder/homefinder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homesapp/', include('homesapp.urls')),

]

django-demo-estate-property/homefinder/homesapp/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.urls import path
from .import views
urlpatterns = [
#  path(r'^$', views.IndexView.as_view(), name = 'index'  ),

    path('<int:pk>/', views.LocatonView.as_view(), name = 'property'),
    path('<int:cpk>/<int:pk>/', views.PropertyDetail.as_view(), name = 'propertyview'),

]

django-demo-estate-property/homefinder/homesapp/models.py
from django.db import models
# Create your models here.


class Location(models.Model):
    location_name = models.CharField(max_length = 200)
    location_type = models.CharField(max_length = 200)

    def __str__(self):
        return self.location_name


class Property(models.Model):
    location = models.ForeignKey(Location, on_delete = models.CASCADE)
    property_name = models.CharField(max_length = 200)
    area = models.CharField (max_length = 200)
    age = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    direction = models.CharField(max_length=200)
    floor = models.CharField(max_length=200)
    postadress = models.CharField(max_length=200)
    image_url = models.CharField(max_length=500)

    def __str__(self):
        return self.property_name

django-demo-estate-property/homefinder/homesapp/views.py
from django.shortcuts import render
from django.views import generic
from .models import Location
from .models import Property
# Create your views here.

class IndexView(generic.ListView):
    template_name = 'homesapp/index.html'

    def get_queryset(self):
        return Location.objects.all()


class LocatonView(generic.DetailView):
    model = Location
    template_name = 'homesapp/locationview.html'


class PropertyDetail(generic.DetailView):
    model = Property
    template_name = 'homesapp/propertyview.html'

django-demo-estate-property/homefinder/homesapp/templates/homesapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        nav {
        background-color:black
        }


    </style>
    <title></title>
</head>
<body><nav class="navbar bg-dark">
  <a class="navbar" href="#">Property Arena</a>
    <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
    </ul>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Page 1</a></li>
    </ul>
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Page 2</a></li>
    </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Sing Up </a></li>
    </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Log In</a></li>
    </ul>




</nav>

 {% block body %}
 {% endblock %}
</body>
</html>

django-demo-estate-property/homefinder/homesapp/templates/homesapp/index.html
{% extends 'homesapp/base.html' %}

{% block body %}
<html>
<head>

</head>
<body>
<div class="container">
    <div class="jumbotron">
        <h1>
            Property Arena
        </h1>
        <p>
            Find the best properties across all the locations.
        </p>

    </div>
</div>
<center>
    <h1>
        Select your location:
    </h1>
    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panael panel-heading">
                Locations:

    {% for location in object_list %}
  <div class="panel-body">  <a href="/homesapp/{{location.id}}"> {{location.location_name }} </a>

    <br>
       </div>
{% endfor %}

            </div>
        </div>

    </div>
</center>
</body>
{% endblock %}
</html>

django-demo-estate-property/homefinder/homesapp/templates/homesapp/locationview.html
{% extends 'homesapp/base.html' %}
 {% block body %}
<html>
<head>
<style>
 .table {
 border: 1px solid blue;
 }
  .panel-heading{
        background-color:blue;
        }

</style>
</head>
<body>
<div class="col-md-1">

</div>f
<div class="col-md-8">
 <h1>
  Properties in {{ location.location_name }}
 </h1>


{% for place in location.property_set.all  %}
  <div class="panel-group">
   <div class="panel panel-primary">
    <div class="panel-heading">
     {{place.property_name }}
    </div>
    <div class="panel-body">
     <div class="col-md-4">
      <img src="{{place.image_url}}" height="200" width="200" alt="">
     </div>
     <div class="col-md-6">
      <table class="table">
       <tbody>
       <tr>
        <td>
         <label>
          <b>AREA SQFT</b>
         </label>
        </td>
        <td>{{place.area}}</td>
       </tr>
         <tr>
        <td>
         <label>
          <b>Price</b>
         </label>
        </td>
        <td>{{place.price}}$</td>
       </tr>
         <tr>
        <td>
         <label>
          <b>Floors</b>
         </label>
        </td>
        <td>{{place.floor}}</td>
       </tr>
         <tr>
        <td>
         <label>
          <b>Post Address</b>
         </label>
        </td>
        <td>{{place.postadress}}</td>
       </tr>
         <tr>
        <td>
         <label>
          <b>Direction</b>
         </label>
        </td>
        <td>{{place.direction}}</td>
       </tr>
         <tr>
        <td>
         <label>
          <b>Age</b>
         </label>
        </td>
        <td>{{place.age}} years</td>
       </tr>
       <tr>
        <td></td>
        <td></td>
        <td> <a class="btn btn-success" href=" /homesapp/{{location.id}}/{{place.id}}">
         View Details
        </a></td>
       </tr>
       </tbody>
      </table>
     </div>
    </div>
   </div>
   {% endfor %}
  </div>

</div>
</body>
</html>
<a href="/homesapp/{{location.id}}/{{place.id}}"> {{place.property_name   }}</a>


{% endblock %}

django-demo-estate-property/homefinder/homesapp/templates/homesapp/propertyview.html
{% extends 'homesapp/base.html' %}
{% block body %}
<html>
<head>
    <style>
        .table {
        border: 1px solid blue;
        }
        .panel-heading{
        background-color:blue;
        }
         #map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }

    </style>
</head>

<body>
<div class="row">
    <div class="col-md-1">

    </div>
    <div class="col-md-3">
        <div class="thumbnail">
            <img src="{{property.image_url}}" height="420" width="420" alt="">
            <div class="caption">
                <p>
                    {{property.property_name }}
                </p>
            </div>

        </div>
    </div>
    <div class="col-md-8">
        <div class="container">
            <div class="panel-group">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Property Details
                    </div>
                    <div class="panel-body">
                        <table class="table">
                            <tbody>
                            <tr>
                                <td>
                                    <label>
                                        <b>
                                            Area SQFT
                                        </b>
                                    </label>
                                </td>
                                        <td>
                                    {{property.area}}
                                        </td>


                            </tr>
                             <tr>
                                <td>
                                    <label>
                                        <b>
                                           Price
                                        </b>
                                    </label>
                                </td>
                                        <td>
                                    {{property.price}}$
                                        </td>


                            </tr>
                             <tr>
                                <td>
                                    <label>
                                        <b>
                                           Age
                                        </b>
                                    </label>
                                </td>
                                        <td>
                                    {{property.age}} years
                                        </td>


                            </tr>
                             <tr>
                                <td>
                                    <label>
                                        <b>
                                           Direction
                                        </b>
                                    </label>
                                </td>
                                        <td>
                                    {{property.direction}}
                                        </td>


                            </tr>
                             <tr>
                                <td>
                                    <label>
                                        <b>
                                           Floors
                                        </b>
                                    </label>
                                </td>
                                        <td>
                                    {{property.floor}}
                                        </td>


                            </tr>
                             <tr>
                                <td>
                                    <label>
                                        <b>
                                           Post Address
                                        </b>
                                    </label>
                                </td>
                                        <td>
                                    {{property.postadress}}
                                        </td>


                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!--map starts here !-->

<div class="col-md-8">
    <div class="thumbnail">
        <h3>
            Location:
        </h3>
         <div id="map"></div>
    <script>
//Initialize and add the map
function initMap() {
  // The location of Uluru
  var uluru = {lat: -25.344, lng: 131.036};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 4, center: uluru});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: uluru, map: map});
}
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9nIkNEFxQDFtiGQLOaLxqI2P8w8dxDhQ&callback=initMap">
    </script>

    </div>
</div>

</body>
</html>





{% endblock %}